1 login frontend
INF2-3/application pull request #33
Opened 2023-02-24 14:15 UTC by FrancaBaars

2023-03-06 13:12 UTC, Jessev3 reviewed
Schaalt alles wel goed als het scherm gemaximaliseerd wordt?

2023-03-06 13:13 UTC, Mappeldorn requested changes

2023-03-06 13:13 UTC, Mappeldorn commented on Quintor/src/main/resources/com/example/quintor/login.fxml
> +            <TextField fx:id="passwordField" layoutX="80.0" layoutY="140.0" minHeight="40.0" minWidth="400.0" prefHeight="40.0" prefWidth="400.0" promptText="Wachtwoord" style="-fx-border-color: blac
Kan je ervoor zorgen dat het wachtwoord niet zichtbaar is bij het typen van het wachtwoord

https://www.youtube.com/watch?v=8jBvF5RgELc

2023-03-06 13:15 UTC, Mappeldorn commented
Kan je in de MainApplication.java navbar.fxml veranderen naar login.fxml

2023-03-06 19:36 UTC, Mappeldorn approved these changes

2023-03-07 08:33 UTC, Jessev3 approved these changes

2023-03-07 08:33 UTC, merged