4 create user frontend
INF2-3/application pull request #35
Opened 2023-03-07 15:01 UTC by FrancaBaars

2023-03-07 20:55 UTC, Mappeldorn requested changes

2023-03-07 20:55 UTC, Mappeldorn commented on Quintor/src/main/java/com/example/quintor/AddUserController.java
> +public class AddUserController {
Gebruik de naam createUser, dit komt ook overeen met de naamgeving van CRUD(create, read, update en delete). ook kan de methode makeUser() worden veranderd naar createUser.

2023-03-17 12:28 UTC, Jessev3 approved these changes

2023-03-17 12:47 UTC, Mappeldorn approved these changes

2023-03-17 12:48 UTC, merged