8 bank statement details
INF2-3/application pull request #36
Opened 2023-03-08 12:17 UTC by Mappeldorn

2023-03-09 09:05 UTC, FrancaBaars requested changes

2023-03-09 09:05 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
>          fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("MT940 files", "*.940"));
Nog een comment aan deze methode toevoegen graag.

2023-03-09 09:05 UTC, FrancaBaars commented on Quintor/src/main/resources/com/example/quintor/bankStatementDetailed.fxml
> +        <Button fx:id="dashboardButton" layoutX="1157.0" layoutY="663.0" mnemonicParsing="false" onAction="#test" prefHeight="36.0" prefWidth="150.0" style="-fx-background-color: #023047; -fx-font-we
Hier het id en de onaction graag weghalen, hij werkt op dit moment niet

2023-03-09 09:05 UTC, FrancaBaars commented on Quintor/src/main/resources/com/example/quintor/navbar.fxml
> +<?import javafx.scene.control.Label?>
Hier graag de ongebruikte imports weghalen

2023-03-17 13:05 UTC, FrancaBaars requested changes

2023-03-17 13:05 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
>  import javafx.event.ActionEvent;
Er zijn hier nog ongebruikte imports deze graag weghalen

2023-03-17 13:05 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
> +
Deze witregel graag weer weghalen

2023-03-17 13:20 UTC, FrancaBaars approved these changes

2023-03-22 10:07 UTC, Jessev3 approved these changes

2023-03-22 10:07 UTC, merged