5 save file
INF2-3/application pull request #37
Opened 2023-03-15 10:01 UTC by FrancaBaars

2023-03-16 11:50 UTC, Noizeisdead approved these changes

2023-03-16 12:26 UTC, Mappeldorn requested changes

2023-03-16 12:26 UTC, Mappeldorn commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
> +        String url = "http://localhost:8080/api/mt940/insert";
Je kan nog een .env bestand aanmaken waar de url voor de api(http://localhost:8080). zet dit bestand dan ook in de gitignore

2023-03-17 10:23 UTC, Mappeldorn approved these changes

2023-03-17 10:23 UTC, merged