16 transactie gegevens
INF2-3/application pull request #38
Opened 2023-03-15 10:10 UTC by Noizeisdead

2023-03-15 13:01 UTC, FrancaBaars requested changes

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/LoginController.java
>  import javafx.stage.Stage;
Op regel 11 staat een import die niet gebruikt wordt.

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/LoginController.java
>          //For the demo
Denk dat deze regel nog weg moet

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/MainApplication.java
> +import java.util.Set;
Deze wordt niet gebruikt

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/MainApplication.java
> +        stage.setTitle("quintor");
Dit is mooier met een hoofdletter denk ik. Of misschien zelfs met een field met daar de naam van de applicatie in?

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
> +        TransactionOverviewController transactionOverviewController = new TransactionOverviewController();
Deze variabele wordt niet gebruikt

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
> +        SettingsController settingsController = new SettingsController();
Deze variabele wordt niet gebruikt

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
> +
Deze lege regels kunnen wel weg

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
> +        window.setScene(new Scene(root));
Zou je dit stukje code misschien een aparte methode kunnen maken met een parameter, dit wordt in dit bestand namelijk 3x bijna hetzelfde getypt

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/SettingsController.java
> +import javafx.fxml.Initializable;
Hier ook graag alle ongebruikte imports weghalen

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
> +    public void showStage() {
Deze methode wordt nergens gebruikt?

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/NavbarController.java
>          } catch (IOException ex) {
De methode op regel 112 wordt nu nergens meer gebruikt, kan deze dan weg, of gaan we hem nog ergens anders gebruiken?

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/SettingsController.java
> +    public static void showStage() {
Deze methode wordt nergens gebruikt, gaan we die nog ergens voor gebruiken?

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/SettingsController.java
> +    public void initialize(URL url, ResourceBundle resourceBundle) {
Deze methode heeft geen inhoud? Moet deze klasse dan die interface implementen, als we hem toch niet gebruiken? Of zou dat later nog ingevuld moeten worden?

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionInformationController.java
> +import javafx.scene.layout.AnchorPane;
Deze import wordt niet gebruikt, graag weghalen

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionInformationController.java
> +    public void initialize(URL url, ResourceBundle resourceBundle) {
Hier dezelfde vraag als bij Settingscontroller

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionInformationController.java
> +    public void initialize(URL url, ResourceBundle resourceBundle) {
Ook voor de methodes hieronder

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionOverviewController.java
> +        TransactionInformationController transactionInformationController = new TransactionInformationController();
Deze variabele wordt nergens gebruikt

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionOverviewController.java
> +        window.setScene(new Scene(root));
en deze regels zijn weer bijna hetzelfde als navbar controller, zou dan 1 statische methode kunnen worden

2023-03-15 13:01 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/TransactionOverviewController.java
> +
Lege regels kunnen wel weggehaald worden

2023-03-15 13:09 UTC, Mappeldorn approved these changes

2023-03-16 08:32 UTC, FrancaBaars approved these changes

2023-03-16 08:40 UTC, merged