28 api connection
INF2-3/application pull request #39
Opened 2023-03-17 10:22 UTC by Mappeldorn

2023-03-17 10:39 UTC, FrancaBaars requested changes

2023-03-17 10:39 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/ApiService.java
> +        setUrl("http://localhost:8080/MT940toJSON");
Hier ook graag de .env file gebruiken voor het stukje "http://localhost:8080"

2023-03-17 10:39 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/ApiService.java
> +        return response.toString();
Deze regels zijn precies hetzelfde als regel 40 tm 49 is er een manier waardoor dit in een aparte methode kan worden gezet?

2023-03-17 10:39 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/ApiService.java
Graag nog javadoc boven de methodes zetten

2023-03-17 10:39 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/ApiService.java
> +import java.net.ProtocolException;
Dit is nog een ongebruikte import

2023-03-17 10:39 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/ApiService.java
> +            case "post":
Is het een idee om hier een enum voor te gebruiken, zodat we het afdwingen dat ze get of post moeten gebruiken

2023-03-17 12:55 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/services/ApiService.java
> +    public void setUrl(String url) {
Ik vind het zelf altijd wel netjes om een null en .isempty check te doen op de setter van een string. Dit zou je nog kunnen toevoegen

2023-03-17 13:19 UTC, FrancaBaars approved these changes

2023-03-22 10:08 UTC, Jessev3 approved these changes

2023-03-22 10:08 UTC, merged