6 naar postgres
INF2-3/application pull request #42
Opened 2023-04-03 09:18 UTC by Noizeisdead

2023-04-04 08:26 UTC, Mappeldorn requested changes

2023-04-04 08:26 UTC, Mappeldorn commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
>                      System.out.println("gelukt");
System.out.println() kan weg

2023-04-04 08:26 UTC, Mappeldorn commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
>                      System.out.println("niet gelukt");
System.out.println() kan weg

2023-04-04 08:26 UTC, Mappeldorn commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
> +        System.out.println(System.getenv("URL_API"));
System.out.println() kan ook weg

2023-04-04 09:12 UTC, Mappeldorn approved these changes

2023-04-05 07:49 UTC, FrancaBaars requested changes

2023-04-05 07:49 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
> +                    uploadToPostgres(f, userId);
Je kan deze methode wel aan de if statement toevoegen, dat beide goed moeten gaan, voordat er iets anders gebeurt. Ook omdat je de methode wel een boolean laat returnen

2023-04-05 07:49 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
De ongebruikte imports graag nog even weghalen

2023-04-05 07:49 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
>                  } else {
Er moet denk ik wel iets gebeuren als het uploaden niet gelukt is. Moeten we even overleggen

2023-04-05 07:49 UTC, FrancaBaars commented on Quintor/src/main/java/com/example/quintor/DashboardController.java
> +    private boolean uploadToPostgres(File file, int userId) throws IOException {
Wil je nog comment toevoegen wat de methode doet.

2023-04-06 08:21 UTC, FrancaBaars approved these changes

2023-04-06 08:29 UTC, merged